export const SIGNUP_PAGE_SUBMITTED = "SIGNUP_PAGE_SUBMITTED";
export const SIGNIN_PAGE_SUBMITTED = "SIGNIn_PAGE_SUBMITTED";
export const RECORD_ADD_SUCCESS = "RECORD_ADD_SUCCESS";
export const RECORD_ADD_FAILURE = "RECORD_ADD_FAILURE";
export const COMPANY_FETCH_SUBMITTED = "COMPANY_FETCH_SUBMITTED";
export const COMPANY_FETCH_SUCCESS = "COMPANY_FETCH_SUCCESS";
export const COMPANY_FETCH_FAILURE = "COMPANY_FETCH_FAILURE";